#!/usr/bin/env just --justfile

set shell := ["bash", "-euo", "pipefail", "-c"]

export ROOT_DIR := shell('dirname "$(readlink --canonicalize "${BASH_SOURCE:-$0}")"')
export PROJECT := "{{ cookiecutter.__project_slug }}"
export USER_UID := shell('id --user')
export USER_GID := shell('id --group')

DOCKER_COMPOSE_FILE := "./compose.yaml"
DOCKER_COMPOSE_CMD := "docker compose"
DOCKER_RUN_CMD := env("DOCKER_RUN_CMD", "/usr/bin/dumb-init -- bash")

DOCKER_BUILD_ARGS := ("--progress=plain"
    + " --build-arg BASE_IMAGE='ubuntu:22.04'"
    + " --build-arg USER_UID='"
    + USER_UID
    + "' --build-arg USER_GID='"
    + USER_GID
    + "' --build-arg GIT_COMMIT='"
    + shell('git show --no-patch --format=%H 2>/dev/null || echo "no_git"')
    + "' --build-arg GIT_COMMIT_DATE='"
    + shell('git show --no-patch --date=iso8601 --format=%ci 2>/dev/null || echo "no_git"')
    + "' --build-arg PROJECT='"
    + PROJECT
    + "' --build-arg IMAGE_NAME='"
    + PROJECT
    + "' --build-arg BUILD_DATE='"
    + shell('date --iso-8601=seconds')
    + "'")

# Section. --- {{ "{{{" }}

# Default recipe.
all: dev check build test format

# Development setup.
dev:
    cp --recursive --force ./other/git/hooks/* ./.git/hooks/

# Start containers.
up:
    〘 DOCKER_COMPOSE_CMD 〙 --file 〘 DOCKER_COMPOSE_FILE 〙 up --detach

# Stop and remove containers.
down:
    〘 DOCKER_COMPOSE_CMD 〙 --file 〘 DOCKER_COMPOSE_FILE 〙 down --remove-orphans

# Remove all containers matching project name.
down_all_containers:
    docker ps --all --filter "name=〘 PROJECT 〙" --format "〘〘.ID〙" \
            | xargs --no-run-if-empty --replace={} docker rm --force {}

# Run container with command.
run:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -t 0 ] && [ -t 1 ]; then
        export DOCKER_STDIN_OPEN=true
        export DOCKER_TTY=true
        TTY_FLAG=""
    else
        export DOCKER_STDIN_OPEN=false
        export DOCKER_TTY=false
        TTY_FLAG="--no-TTY"
    fi
    〘 DOCKER_COMPOSE_CMD 〙 \
            --file 〘 DOCKER_COMPOSE_FILE 〙 \
            run \
            --rm \
            ${TTY_FLAG} \
            {{ cookiecutter.__project_slug }} \
            〘 DOCKER_RUN_CMD 〙

# Exec into a running docker.
docker_exec:
    〘 DOCKER_COMPOSE_CMD 〙 exec 〘 PROJECT 〙 〘 DOCKER_RUN_CMD 〙

# Shell access.
shell:

# Build Docker images.
build:
    〘 DOCKER_COMPOSE_CMD 〙 --file 〘 DOCKER_COMPOSE_FILE 〙 build 〘 DOCKER_BUILD_ARGS 〙

# Run checks.
check:

# Run tests.
test:
    set -x ; DOCKER_RUN_CMD='bash -c '"'"'bash -xv ./other/tests/test.sh'"'" just run

# Format all files.
format: format_yaml format_json format_rec

# Format YAML files.
format_yaml:
    find 〘 ROOT_DIR 〙 \( -iname '*.yml' -o -iname '*.yaml' -o -iname '.yamlfmt' \) -type f -print0 | xargs --null --max-args 100 -- yamlfmt

# Format JSON files.
format_json:
    find . -iname '*.json' -print0 | parallel --null --max-args 1 -- 'python3 -m json.tool --sort-keys {} > /tmp/〘 PROJECT 〙_{/}_{#} && mv /tmp/〘 PROJECT 〙_{/}_{#} {}'

# Check and sort recfiles.
format_rec:
    #! /usr/bin/env bash
    set -Eeuo pipefail
    find . -iname '*.rec' -type f -print0 \
        | parallel \
            --no-run-if-empty \
            --null \
            --group \
            --keep-order \
            --jobs $(nproc) \
            --max-args 1 \
            -- \
            '
    set -euo pipefail
    if recfix --check -- {} && recfix --sort -- {}; then
        echo "✔: {}"
    else
        echo "✘: {}"
    fi
    '

#  --- {{ "}}}" }}

# vim: set foldmethod=marker fileformat=unix filetype=just nowrap foldmarker=⟨⟨⟨,⟩⟩⟩ :
